export const EXEC_DEVICE = 'EXEC_DEVICE';
export const EXEC_ADB = 'EXEC_ADB';
export const OPEN_ADB_SHELL = 'OPEN_ADB_SHELL';
export const OPEN_ADB = 'OPEN_ADB';
export const OPEN_EMULATOR = 'OPEN_EMULATOR';
export const EXEC_LIST_SETTINGS = 'EXEC_LIST_SETTINGS';
export const SAVE_HISTORY = 'SAVE_HISTORY';
export const EXEC_MONKEY = 'EXEC_MONKEY';
export const EXEC_EMULATOR = 'EXEC_EMULATOR';

export const GET_BATTERY = 'GET_BATTERY';
export const GET_PROPS = 'GET_PROPS';
export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SYSTEM = 'GET_SETTINGS_SYSTEM';
export const GET_SETTINGS_GLOBAL = 'GET_SETTINGS_GLOBAL';
export const GET_SETTINGS_SECURE = 'GET_SETTINGS_SECURE';
export const GET_FEATURES = 'GET_FEATURES';
export const GET_PACKAGES = 'GET_PACKAGES';

export const TOGGLE_ADB = 'TOGGLE_ADB';
