export const EXEC_DEVICE = 'EXEC_DEVICE';
export const EXEC_ADB = 'EXEC_ADB';
export const OPEN_ADB_SHELL = 'OPEN_ADB_SHELL';
export const OPEN_ADB = 'OPEN_ADB';
export const OPEN_EMULATOR = 'OPEN_EMULATOR';
export const EXEC_LIST_SETTINGS = 'EXEC_LIST_SETTINGS';
export const EXEC_MONKEY = 'EXEC_MONKEY';
export const EXEC_EMULATOR = 'EXEC_EMULATOR';

export const GET_BATTERY = 'GET_BATTERY';
export const GET_PROPS = 'GET_PROPS';
export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SYSTEM = 'GET_SETTINGS_SYSTEM';
export const GET_SETTINGS_GLOBAL = 'GET_SETTINGS_GLOBAL';
export const GET_SETTINGS_SECURE = 'GET_SETTINGS_SECURE';
export const GET_FEATURES = 'GET_FEATURES';
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_DIR = 'GET_DIR';

export const PUT_SETTING_SYSTEM = 'PUT_SETTING_SYSTEM';
export const PUT_SETTING_GLOBAL = 'PUT_SETTING_GLOBAL';
export const PUT_SETTING_SECURE = 'PUT_SETTING_SECURE';
export const SET_PROP = 'SET_PROP';

export const GET_SETTING_SYSTEM = 'GET_SETTING_SYSTEM';
export const GET_SETTING_GLOBAL = 'GET_SETTING_GLOBAL';
export const GET_SETTING_SECURE = 'GET_SETTING_SECURE';
export const GET_PROP = 'GET_PROP';

export const TOGGLE_ADB = 'TOGGLE_ADB';
export const RENEW_TOKEN = 'RENEW_TOKEN';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const OPEN_LINK = 'OPEN_LINK';

export const PULL_FILE = 'PULL_FILE';
export const DELETE_FILE = 'DELETE_FILE';
