export const ADB_SETTINGS_LOAD = 'ADB_SETTINGS_LOAD';
export const ADB_SETTINGS_WRITE = 'ADB_SETTINGS_WRITE';

export const DEVICE_CHANGE = 'DEVICE_CHANGE';

export const TAB_ADD = 'TAB_ADD';
export const TAB_DEL = 'TAB_DEL';

export const LOAD_TOKEN = 'LOAD_TOKEN';
export const WRITE_TOKEN = 'WRITE_TOKEN';

export const WRITE_CONSOLE_SETTINGS = 'WRITE_CONCOLE_SETTINGS';
export const LOAD_CONSOLE_SETTINGS = 'LOAD_CONCOLE_SETTINGS';
export const ADD_HISTORY = 'ADD_HISTORY';
export const WRITE_LINES = 'WRITE_LINES';
export const WRITE_HISTORY_LEN = 'WRITE_HISTORY_LEN';
export const LOAD_HISTORY = 'LOAD_HISTORY';

export const ADB_STATUS = 'ADB_STATUS';
